server:
  port: 8989

#配置数据源
spring:
  profiles:
    active: dev
  datasource:
    # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource
    # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql驱动
    url: jdbc:mysql://localhost:3306/poster-helper?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ll03001360
    hikari:
      connection-timeout: 30000
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5
      # 最小连接数
      maximum-pool-size: 20
      # 最大连接数
      auto-commit: true
      # 自动提交
      idle-timeout: 600000
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP
      # 连接池名字
      max-lifetime: 1800000
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
#  servlet:
#    multipart:
#      max-file-size: 512000 # 文件上传大小限制500kb
#      max-request-size: 51200 # 请求大小限制为500kb


## mybatis 配置

mybatis:
  type-aliases-package: com.wzy.pojo     # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



## mybatis mapper 配置

# 通用 Mapper 配置
mapper:
  mappers: com.wzy.my.mapper.MyMapper
  # 判断username != null 是否追加判断 username != ''
  not-empty: false
  identity: MYSQL


# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
